=== adabagozi/IDEAaS/ideaas-root/ideaas/dao/src/main/resources/resources/validate.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="Config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="BigDataDB">
                    <xs:complexType>
                            <xs:sequence>
                                    <xs:element type="xs:string" name="Server"/>
                                    <xs:element type="xs:integer" name="Port"/>
                                    <xs:element type="xs:string" name="DBName"/>
                                    <xs:element type="xs:string" name="DBUser"/>
                                    <xs:element type="xs:string" name="DBPassword"/>
                            </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="MySQLDB">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ModelDB">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Server"/>
                                        <xs:element type="xs:integer" name="Port"/>
                                        <xs:element type="xs:string" name="DBName"/>
                                        <xs:element type="xs:string" name="DBUser"/>
                                        <xs:element type="xs:string" name="DBPassword"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="MetamodelDB">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Server"/>
                                        <xs:element type="xs:integer" name="Port"/>
                                        <xs:element type="xs:string" name="DBName"/>
                                        <xs:element type="xs:string" name="DBUser"/>
                                        <xs:element type="xs:string" name="DBPassword"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>                   
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>  
             </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== adabagozi/IDEAaS/ideaas-root/ideaas/dao/src/main/resources/resources/serverConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'	xsi:noNamespaceSchemaLocation='validate.xsd'>
    <BigDataDB>
        <Server>localhost</Server> <!-- Potrebbe dare problemi su windows pertanto usare 127.0.0.1 -->
        <Port>27017</Port>
        <DBName>db_name</DBName>
        <DBUser>user_name</DBUser>
        <DBPassword>password</DBPassword>
    </BigDataDB>
    <MySQLDB>
        <ModelDB>
            <Server>localhost</Server>
            <Port>3306</Port>
            <DBName>db_name</DBName>
            <DBUser>user_name</DBUser>
            <DBPassword>password</DBPassword>
        </ModelDB>
        <MetamodelDB>
            <Server>localhost</Server>
            <Port>3306</Port>
            <DBName>db_name</DBName>
            <!--  <DBName>bodai_metamodel</DBName>-->
            <DBUser>user_name</DBUser>
            <DBPassword>password</DBPassword>
        </MetamodelDB>
    </MySQLDB>
</Config>
